socketio:
  host: localhost
  port: 9092

spring:
  datasource:
    url: jdbc:h2:mem:message
    driverClassName: org.h2.Driver
    username: sa
    password: message
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
